### ISSUE TITLE
Error w share on iPad using chrome

### ISSUE THREAD

**Issue by rodolfomartinez** [Oinweb/fly-django#112]
Summary
This happened when trying to share the first badge
Is this a css error?

![image](https://cloud.githubusercontent.com/assets/7537946/14047415/1a100190-f27e-11e5-9c69-7a77c8361173.png)

**Comment by bartmika** [comment]
No, this is not an error, this ticket is a duplicate of #86. @viralrain  needs to apply CSS/JS beautifucation because right now there is none.

**Comment by rodolfomartinez** [comment]
@bartmika if necessary can we implement some basic CSS and/or get Kanwar involved?

**Comment by bartmika** [comment]
This is not an error. This is the share page.
