### ISSUE TITLE
Quiz screen

### ISSUE THREAD

**Issue by rodolfomartinez** [Oinweb/fly-django#135]
Summary: 

After clicking the quiz button there is a short introduction that says something like

Now the quiz should launch

Can we remove this screen so that after the video if someone clicks the quiz button they go straight into the quiz?

**Comment by bartmika** [comment]
Honestly, better leave @viralrain's code alone.

**Comment by rodolfomartinez** [comment]
OK @bartmika  can we change the text if need to?
