### ISSUE TITLE
Profile > Courses Complete: Credit II is missing

### ISSUE THREAD

**Issue by rodolfomartinez** [Oinweb/fly-django#144]
Summary:
Credit II is missing from this list as per screenshot. Can courses be displayed in this order:

Finances 101
Finances II
Saving & Budgeting
Saving & Bugeting II
Credit 101
Credit II

![screen shot 2016-10-14 at 4 11 56 pm](https://cloud.githubusercontent.com/assets/7537946/19401386/1c545938-9229-11e6-9bc4-f020b45f6c96.png)

**Comment by bartmika** [comment]
Cannot reproduce this error.

![screen shot 2016-10-15 at 3 38 49 pm](https://cloud.githubusercontent.com/assets/5767602/19412902/bc7b442a-92ed-11e6-92b3-082362938d81.png)
