### ISSUE TITLE
Images missing

### ISSUE THREAD

**Issue by rodolfomartinez** [Oinweb/fly-django#158]
Summary:
Images are missing on the courses screen

Please see attached screen shots
![screen shot 2016-11-14 at 8 29 03 pm](https://cloud.githubusercontent.com/assets/7537946/20289671/19967be8-aaa9-11e6-8932-a8bddf325ce9.png)
![screen shot 2016-11-14 at 8 29 10 pm](https://cloud.githubusercontent.com/assets/7537946/20289670/199676b6-aaa9-11e6-8e19-8435f8805d8f.png)

**Comment by bartmika** [comment]
The potential reason this might now work is because we need to run: ``python manage.py collect static``. Let me run it and then confirm it fixes the issue..
